function fitter(){
    let menu=document.getElementById("form1");
    menu.style.display="none";
    let menu1=document.getElementById("form2");
    menu1.style.display="none";
    let menu2=document.getElementById("form3");
    menu2.style.display="none";
    let menu3=document.getElementById("form4");
    menu3.style.display="none";
    let vđ=document.getElementById("vđ")
    vđ.style.display="block";
    let vđ1=document.getElementById("vđ1")
    vđ1.style.display="block";
    let vđ2=document.getElementById("vđ2")
    vđ2.style.display="block";
    let vđ3=document.getElementById("vđ3")
    vđ3.style.display="block";
    let tt=document.getElementById("tt");
    tt.style.display="none";
    let tt1=document.getElementById("tt1");
    tt1.style.display="none";
    let tt2=document.getElementById("tt2");
    tt2.style.display="none";
    let tt3=document.getElementById("tt3");
    tt3.style.display="none";
    let pk=document.getElementById("pk");
    pk.style.display="none";
    let pk1=document.getElementById("pk1");
    pk1.style.display="none";
    let pk2=document.getElementById("pk2");
    pk2.style.display="none";
    let pk3=document.getElementById("pk3");
    pk3.style.display="none";
}
function fitter1(){
    let cv=document.getElementById("form1");
    cv.style.display="block";
    let cv1=document.getElementById("form2");
    cv1.style.display="block";
    let cv2=document.getElementById("form3");
    cv2.style.display="block";
    let cv3=document.getElementById("form4");
    cv3.style.display="block";
    let menu4=document.getElementById("vđ")
    menu4.style.display="none";
    let menu5=document.getElementById("vđ1")
    menu5.style.display="none";
    let menu6=document.getElementById("vđ2")
    menu6.style.display="none";
    let menu7=document.getElementById("vđ3")
    menu7.style.display="none";
    let tt=document.getElementById("tt");
    tt.style.display="none";
    let tt1=document.getElementById("tt1");
    tt1.style.display="none";
    let tt2=document.getElementById("tt2");
    tt2.style.display="none";
    let tt3=document.getElementById("tt3");
    tt3.style.display="none";
    let pk=document.getElementById("pk");
    pk.style.display="none";
    let pk1=document.getElementById("pk1");
    pk1.style.display="none";
    let pk2=document.getElementById("pk2");
    pk2.style.display="none";
    let pk3=document.getElementById("pk3");
    pk3.style.display="none";
}
function fitter2(){
    let cv=document.getElementById("form1");
    cv.style.display="none";
    let cv1=document.getElementById("form2");
    cv1.style.display="none";
    let cv2=document.getElementById("form3");
    cv2.style.display="none";
    let cv3=document.getElementById("form4");
    cv3.style.display="none";
    let menu4=document.getElementById("vđ")
    menu4.style.display="none";
    let menu5=document.getElementById("vđ1")
    menu5.style.display="none";
    let menu6=document.getElementById("vđ2")
    menu6.style.display="none";
    let menu7=document.getElementById("vđ3")
    menu7.style.display="none";
    let tt=document.getElementById("tt");
    tt.style.display="block";
    let tt1=document.getElementById("tt1");
    tt1.style.display="block";
    let tt2=document.getElementById("tt2");
    tt2.style.display="block";
    let tt3=document.getElementById("tt3");
    tt3.style.display="block";
    let pk=document.getElementById("pk");
    pk.style.display="none";
    let pk1=document.getElementById("pk1");
    pk1.style.display="none";
    let pk2=document.getElementById("pk2");
    pk2.style.display="none";
    let pk3=document.getElementById("pk3");
    pk3.style.display="none";
}
function fitterall(){
    let cv=document.getElementById("form1");
    cv.style.display="block";
    let cv1=document.getElementById("form2");
    cv1.style.display="block";
    let cv2=document.getElementById("form3");
    cv2.style.display="block";
    let cv3=document.getElementById("form4");
    cv3.style.display="block";
    let menu4=document.getElementById("vđ")
    menu4.style.display="block";
    let menu5=document.getElementById("vđ1")
    menu5.style.display="block";
    let menu6=document.getElementById("vđ2")
    menu6.style.display="block";
    let menu7=document.getElementById("vđ3")
    menu7.style.display="block";
    let tt=document.getElementById("tt");
    tt.style.display="block";
    let tt1=document.getElementById("tt1");
    tt1.style.display="block";
    let tt2=document.getElementById("tt2");
    tt2.style.display="block";
    let tt3=document.getElementById("tt3");
    tt3.style.display="block";
    let pk=document.getElementById("pk");
    pk.style.display="block";2
    let pk1=document.getElementById("pk1");
    pk1.style.display="block";
    let pk2=document.getElementById("pk2");
    pk2.style.display="block";
    let pk3=document.getElementById("pk3");
    pk3.style.display="block";
}
function fitter3(){
    let cv=document.getElementById("form1");
    cv.style.display="none";
    let cv1=document.getElementById("form2");
    cv1.style.display="none";
    let cv2=document.getElementById("form3");
    cv2.style.display="none";
    let cv3=document.getElementById("form4");
    cv3.style.display="none";
    let menu4=document.getElementById("vđ")
    menu4.style.display="none";
    let menu5=document.getElementById("vđ1")
    menu5.style.display="none";
    let menu6=document.getElementById("vđ2")
    menu6.style.display="none";
    let menu7=document.getElementById("vđ3")
    menu7.style.display="none";
    let tt=document.getElementById("tt");
    tt.style.display="none";
    let tt1=document.getElementById("tt1");
    tt1.style.display="none";
    let tt2=document.getElementById("tt2");
    tt2.style.display="none";
    let tt3=document.getElementById("tt3");
    tt3.style.display="none";
    let pk=document.getElementById("pk");
    pk.style.display="block";
    let pk1=document.getElementById("pk1");
    pk1.style.display="block";
    let pk2=document.getElementById("pk2");
    pk2.style.display="block";
    let pk3=document.getElementById("pk3");
    pk3.style.display="block";
}
// let menu=document.getElementById('form1');
// document.addEventListener('contextmenu',function(event){
//     event.preventDefault();
//     menu.style.display='block';
//     menu.style.top=event.y + 'px';
//     menu.style.left=event.x +'px';
// })
// document.addEventListener('click',function(){
//     menu.style.display='none';
// })